In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
df = pd.read_csv("C:\\Users\\kaudim\\Documents\\Work\\Trainings\\Jupyter playarea\\south_africa_training_set.csv")

In [8]:
df.head(5)

,Unnamed: 0,target,hashed_user_id,regist_date,is_bind_card,lastorder_usecase,lastorder_platform,lastorder_orderdate,subtotal_amount_today_daily,subtotal_amount_recent_7days,...,subtotal_ordercount_recent_30days,nr_interactions,nr_days_interacted,max_date_time,nr_unique_pages_visited,search_events,unique_search_terms,unique_app_visits,unique_app_category_visits,year_month
0,0,active,-1000772633524872632,2022-12-30,0,-1,-1,NaN,0.0,0.0,...,0,15,1,2022-12-30,6,0,0,2,1,202212
1,1,inactive,-1000772633524872632,2022-12-30,0,-1,-1,NaN,0.0,0.0,...,0,11,2,2023-01-20,2,0,0,2,1,202301
2,2,inactive,-1006559301419582051,2022-08-15,0,-1,-1,NaN,0.0,0.0,...,0,4,1,2022-12-06,2,0,0,1,0,202212
3,3,inactive,-1006671521575354929,2023-01-03,0,-1,-1,NaN,0.0,0.0,...,0,35,1,2023-01-03,17,0,0,3,2,202301
4,4,inactive,-1008193142447905044,2021-10-16,1,-1,-1,NaN,0.0,0.0,...,0,158,3,2022-11-21,12,0,0,7,5,202211

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2153657 entries, 0 to 2153656
Data columns (total 23 columns):
 #   Column                             Dtype
---  ------                             -----
 0   Unnamed: 0                         int64
 1   target                             object
 2   hashed_user_id                     int64
 3   regist_date                        object
 4   is_bind_card                       int64
 5   lastorder_usecase                  object
 6   lastorder_platform                 object
 7   lastorder_orderdate                object
 8   subtotal_amount_today_daily        float64
 9   subtotal_amount_recent_7days       float64
 10  subtotal_amount_recent_30days      float64
 11  subtotal_ordercount_today_daily    int64
 12  subtotal_ordercount_recent_7days   int64
 13  subtotal_ordercount_recent_30days  int64
 14  nr_interactions                    int64
 15  nr_days_interacted                 int64
 16  max_date_time                      object
 17  nr_unique_pages_visited            int64
 18  search_events                      int64
 19  unique_search_terms                int64
 20  unique_app_visits                  int64
 21  unique_app_category_visits         int64
 22  year_month                         int64
dtypes: float64(3), int64(14), object(6)
memory usage: 377.9+ MB

In [12]:
new_df = df.dropna()

In [13]:
print(new_df)

         Unnamed: 0    target       hashed_user_id regist_date  is_bind_card
6                 6    active -1020500780636001202  2022-04-07             1  \
7                 7    active -1020500780636001202  2022-04-07             1
8                 8    active -1020500780636001202  2022-04-07             1
9                 9  inactive -1020500780636001202  2022-04-07             1
10               10    active -1025425308758786705  2021-11-21             1
...             ...       ...                  ...         ...           ...
2153622     2153622    active    95097497918093510  2022-11-21             1
2153629     2153629  inactive   963646214867459441  2023-01-06             0
2153630     2153630    active   971885533578456688  2022-11-08             0
2153635     2153635    active   972683467600165652  2022-03-09             0
2153636     2153636  inactive   972683467600165652  2022-03-09             0

        lastorder_usecase lastorder_platform lastorder_orderdate
6                  MOBILE           electrum          2022-10-19  \
7                  MOBILE           electrum          2022-11-29
8                  MOBILE           electrum          2022-12-18
9                  MOBILE           electrum          2022-12-18
10                 MOBILE           electrum          2022-11-15
...                   ...                ...                 ...
2153622            MOBILE           electrum          2022-12-10
2153629            MOBILE           electrum          2023-01-06
2153630            MOBILE           electrum          2022-11-11
2153635            MOBILE           electrum          2022-11-25
2153636            MOBILE           electrum          2022-11-25

         subtotal_amount_today_daily  subtotal_amount_recent_7days  ...
6                                0.0                           0.0  ...  \
7                                0.0                          11.0  ...
8                                0.0                           0.0  ...
9                                0.0                           0.0  ...
10                               0.0                           0.0  ...
...                              ...                           ...  ...
2153622                          0.0                           0.0  ...
2153629                          0.0                           0.0  ...
2153630                          0.0                           0.0  ...
2153635                          0.0                          46.0  ...
2153636                          0.0                           0.0  ...

         subtotal_ordercount_recent_30days  nr_interactions
6                                        2              393  \
7                                        3              391
8                                        1              241
9                                        0               86
10                                       2              112
...                                    ...              ...
2153622                                  1              176
2153629                                  1               38
2153630                                  7              353
2153635                                  1               60
2153636                                  0               48

         nr_days_interacted  max_date_time  nr_unique_pages_visited
6                        17     2022-10-24                       20  \
7                        15     2022-11-30                       20
8                        12     2022-12-25                       17
9                         5     2023-01-28                       11
10                        5     2022-11-20                       17
...                     ...            ...                      ...
2153622                   7     2022-12-29                       25
2153629                   2     2023-01-13                       14
2153630                  14     2022-11-25                       16
2153635                   3     2022-11-28                       12
2153636                   4     2022-12-05                       10

         search_events unique_search_terms  unique_app_visits
6                    0                   0                  4  \
7                    0                   0                  5
8                    0                   0                  3
9                    0                   0                  2
10                   0                   0                  1
...                ...                 ...                ...
2153622              0                   0                  5
2153629              0                   0                  2
2153630              0                   0                  5
2153635              0                   0                  4
2153636              0                   0                  4

         unique_app_category_visits  year_month
6                                 2      202210
7                                 3      202211
8                                 2      202212
9                                 1      202301
10                                0      202211
...                             ...         ...
2153622                           3      202212
2153629                           1      202301
2153630                           3      202211
2153635                           2      202211
2153636                           2      202212

[590889 rows x 23 columns]